name: RemoteRepo
on:
 
  workflow_dispatch:  
   inputs:
      aa:
        description: 'country'
        required: true
        default: 'USA'
        type: choice
        options:
        - Australia
        - UK
        - Russia
      bb:
        description: 'month'
        required: true
        default: 'aug'
        type: choice
        options:
        - sep
        - oct
        - nov
        

jobs: 
 differentrepo_job:
  runs-on: ubuntu-latest
  env:
   Greeting: Hello
   
  steps:
   - name: notificationJob_ScriptToExecute
     run: |
       echo "AAAA"  
       sleep 120
